---
services:
  s-ui:
    build: .
    container_name: s-ui-dev
    hostname: "s-ui-dev"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    networks:
      - s-ui
    entrypoint: "./entrypoint.sh"

networks:
  s-ui:
    driver: bridge

